apiVersion: apps/v1
kind: Deployment
metadata:
  name: daily-memes-bot
  labels:
    app.kubernetes.io/name: daily-memes-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: daily-memes-bot
  template:
    metadata:
      labels:
        app.kubernetes.io/name: daily-memes-bot
    spec:
      containers:
        - name: daily-memes-bot
          image: mkhamkha/daily-memes-bot:latest # собираем обрез руками, храним в docker репозитории.
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          env:
            - name: JAVA_OPTS
              value: "-XX:+UseContainerSupport -XX:InitialRAMPercentage=70 -XX:MaxRAMPercentage=70"
          envFrom:
            - configMapRef:
                name: cm-daily-memes-bot
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "512Mi"
