apiVersion: v1
kind: Service
metadata:
  name: daily-memes-bot
  labels:
    app.kubernetes.io/name: daily-memes-bot
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: daily-memes-bot
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
